{% set name = "tszip" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 292e16a02086e10771847b7041fa30cd8c11b6f6cf5f841da745085afb1e3d06

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tszip=tszip.cli:tszip_main
    - tsunzip=tszip.cli:tsunzip_main
  noarch: python

requirements:
  host:
    - setuptools
    - setuptools_scm
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - tskit >=0.3.3
    - numcodecs >=0.6.4
    - zarr <3
    - humanize

test:
  commands:
    - tszip -h
    - tsunzip -h
  imports:
    - tszip

about:
  home: http://github.com/tskit-dev/tszip
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Gzip-like compression utility for tskit tree sequences.
  description: |
    Tszip provides high-levels of compression for tskit tree sequence
    files, via a simple Python API and gzip-like command line interface.
  doc_url: https://tskit.dev/tszip/docs
  dev_url: https://github.com/tskit-dev/tszip

extra:
  recipe-maintainers:
    - jeromekelleher
    - benjeffery
