travis:
  secure:
    BINSTAR_TOKEN: MTWeUQ3UW3zAP0X8qB1eQNTtnekSVON2wFOmyfnxZe3re3ne3RFxKGkwrdyCNbF5XIDt4BVTy99nyjz4TUMiIclN105pjK7kbsDNcooGanU2vO+NW9M5O7dNXe9P/aDDuVerp+2ldCfFOycXy+uf1SbYCZ5kqm7TmLdwCFR/UW5Y0/SwKSgQ70weR9Er2M8koZvn6umyJAOEAqZobLfYmqrgzu3JBlBxQfMwzkKB5YKBctP8+odqszJH3UV6jWnby2tP2lriB8d0i3XovGGZlT05kxf61OD53wMBwiA9HjK1zH2hAff+jiozgi0icDoFFmmf97yS6imzdqlSvFeMLNVzPeMJHYPBP7GhecedcycxpUFyqPPcm3ObYBmTfmPWKKCg+YxqbYLtKq618q+VowuU1ADkLs+/+Xqyh5xKksg2PUmN9tuGzr/MVdYf2ni3yU9KXrJ2+1JPBzy98wT1euIc/PE/XYLRRul755E9ddWK17FdUUCJcKM6BGV5LNRn60cXkT1gK37kZX7CPRcNxGKpkpDJLny/0891tLZjBWxGjgi0pfTszrro2acFCspU2p4H7jvNeA8O4heFjehSNdqZeGgufxtnPuR543MbGGu0dZQlGvnj1qyIfK2I6g8F4o4phjNtIOCfRWzYquTiy/BGTpoOqj6IQU9EHw7C5t0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
